# Docker Compose configuration for the 'group7-python-project' project.
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: ["./scripts/wait_for_db.sh", "localhost", "gunicorn", "personal_assistant.wsgi:application", "--bind", "0.0.0.0:8002"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    # Не публикуем порт наружу

volumes:
  postgres_data: